version: '3.7'

x-default-opts:
  &default-health-check
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s

services:

  mysql:
    image: mysql:5.7.32
    deploy:
      <<: *default-health-check
      replicas: 1
      placement:
        constraints:
          - node.labels.application == true
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
    networks:
      - database
      - globalnetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    deploy:
      <<: *default-health-check
      replicas: 1
      placement:
        constraints:
          - node.labels.monitoring == true
    environment:
      PMA_HOST: localhost
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "9094:80"
    networks:
      - database
      - globalnetwork

networks:
  globalnetwork:
    external: true
  database:
    external: true
