version: '3'
services:
  haproxy:
    image: haproxy:2.4.1-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - 80:80


  customer-service:
    container_name: customer-service
    image: account-service:1-SNAPSHOT


  message-service:
    container_name: message-service
    image: message-service:1-SNAPSHOT
    ports:
    - 9090:9090
