version: '2'
services:
  mysql:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 3
      response_timeout: 5000
      port: 3306
  phpmyadmin:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 3
      response_timeout: 5000
      port: 80